services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "OrderFlow_StrongPassword_123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:4-management
    container_name: orderflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  sqlserver_data: